[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/v1/latest-prices.json"
  to = "/.netlify/functions/latest-prices"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/price.json"
  to = "/.netlify/functions/price"
  status = 200
  force = true
